export const configImg = {
  GAME_BG: 'assets/img/bg.png',
  START_SCREEN: 'assets/img/scr1.png',
  BUTTON_START: 'assets/img/button.png',
  WALL: 'assets/img/wall.png',
  BRICK: 'assets/img/small_wall_1.png',
  EAGLE: 'assets/img/eagle.png',
  BONUS_IMMORTAL: 'assets/img/bonus_immortal.png',
  BONUS_LIFE: 'assets/img/bonus_live.png',
  BONUS_SLOW: 'assets/img/bonus_slow.png',
  BONUS_SPEED: 'assets/img/bonus_speed.png',
  BULLET: 'assets/img/bullet.png',
  ENEMY_BULLET: 'assets/img/enemy_bullet.png',
  ENEMY_BLUE: 'assets/img/enemy_blue.png',
  ENEMY_RED: 'assets/img/enemy_red.png',
  ENEMY_WHITE: 'assets/img/enemy_white.png',
  LEAVES: 'assets/img/leaves.png',
  LOADER_BAR: 'assets/img/loader-bar.png',
  LOADER_BG: 'assets/img/loader-bg.png',
  SCORES: 'assets/img/scores.png',
  TANK: 'assets/img/tank.png',
  WATER: 'assets/img/water.png',
};
